name: Tests

on: [push]

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check forge version
        run: nix develop --command forge --version

      - name: Check slither version
        run: nix develop --command slither --version
